"""fix

Revision ID: 1cc485d82354
Revises: 7564b370f431
Create Date: 2025-03-29 21:37:32.712313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc485d82354'
down_revision: Union[str, None] = '7564b370f431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('timetables_subject_id_fkey', 'timetables', type_='foreignkey')
    op.create_foreign_key(None, 'timetables', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.create_foreign_key('timetables_subject_id_fkey', 'timetables', 'teachers', ['subject_id'], ['id'])
    # ### end Alembic commands ###
