"""add student classes

Revision ID: 7564b370f431
Revises: 5e8d10d5ae8e
Create Date: 2025-03-29 14:45:31.299009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7564b370f431'
down_revision: Union[str, None] = '5e8d10d5ae8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['id'])
    op.drop_column('students', 'token')
    op.add_column('timetables', sa.Column('class_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'timetables', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.drop_column('timetables', 'class_id')
    op.add_column('students', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'class_id')
    op.drop_table('classes')
    # ### end Alembic commands ###
