"""fix

Revision ID: fdb0f260bbf1
Revises: 22716132168b
Create Date: 2025-03-30 15:56:03.290971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb0f260bbf1'
down_revision: Union[str, None] = '22716132168b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notes_student_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_student_id_fkey', 'notes', 'notes', ['student_id'], ['id'])
    # ### end Alembic commands ###
